#!/usr/bin/env python

from __future__ import (
    division,
    unicode_literals,
    print_function,
    absolute_import
)

import subprocess
import shlex
import sys
import os

REPO_ROOT = os.getcwd()

def main():
    generate_toc_list_exit_code = subprocess.call("./docs/bin/generate-toc-list")
    if not carbon_jsdoc_exit_code:
        git_cmd = shlex.split("git add %s" % os.path.join(REPO_ROOT, "docs/ref/index.rst"))
        git_exit_code = subprocess.call(git_cmd)

    return generate_toc_list_exit_code or git_exit_code

if __name__ == '__main__':
    sys.exit(main())
